name: Docs website

# build the documentation whenever there are new commits on docs
on:
  push:
    branches:
      - docs

jobs:
  # Build the documentation and upload the static HTML files as an artifact.
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - run: pip install pdoc
      - run: pdoc ./vprdb -o ./docs

      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: ./docs
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TARGET_DIR: ./docs
          MESSAGE: "Updating the website with documentation"
